#!/bin/sh

user="username"

idx=1

lines=`wc -l /yourpath/automated-test-framework/cases/scripts/hosts_list | awk '{print $1}'`

echo $lines

ret=0

while [ $idx -le $lines ]
do
	ip=`cat /yourpath/automated-test-framework/cases/scripts/hosts_list | sed -n "${idx}p"`

	ssh $user@$ip "collie vdi create vvv$idx 1G"

	ret_this=$?

	ret=`expr $ret + $ret_this` 
	
	idx=`expr $idx + 1`
done

exit $ret


