#!/bin/sh

set -x

user="wujue.yht"

idx=1

lines=`wc -l /home/wujue.yht/test/tfw-test/automated-test-framework/cases/scripts/hosts_list | awk '{print $1}'`

echo $lines

ret=0

while [ $idx -le $lines ]
do
	ip=`cat /home/wujue.yht/test/tfw-test/automated-test-framework/cases/scripts/hosts_list | sed -n "${idx}p"`

	ssh $user@$ip "collie vdi create vvvv$idx 1G" &

	ret_this=$?

	ret=`expr $ret + $ret_this` 
	
	idx=`expr $idx + 1`
done

exit $ret


