#!/bin/sh

user="root"

idx=1

lines=`wc -l /home/wujue.yht/test/tfw-test/automated-test-framework/cases/scripts/hosts_list | awk '{print $1}'`

echo $lines

ret=0

while [ $idx -le 2 ]
do
	ip=`cat /home/wujue.yht/test/tfw-test/automated-test-framework/cases/scripts/hosts_list | sed -n "${idx}p"`

	spid=`ssh $user@$ip ps -ef | grep sheep | sed -n '{1p}' | awk '{print $2}'`

	ret_this=$?

	ret=`expr $ret + $ret_this` 

	ssh $user@$ip "kill $spid"

	ret_this=$?

	ret=`expr $ret + $ret_this` 
	
	idx=`expr $idx + 1`
done

exit $ret


