#!/bin/sh

user="root"

idx=1

lines=`wc -l /home/wujue.yht/test/tfw-test/automated-test-framework/cases/scripts/hosts_list | awk '{print $1}'`

echo $lines

ret=0

while [ $idx -le $lines ]
do
	ip=`cat /home/wujue.yht/test/tfw-test/automated-test-framework/cases/scripts/hosts_list | sed -n "${idx}p"`

	ssh $user@$ip "/home/wujue.yht/sheepcode/sheepdog/sheep/sheep /store/tempfailtest"

	ret_this=$?

	ret=`expr $ret + $ret_this` 
	
	idx=`expr $idx + 1`
done

exit $ret


